title: Kyle Coughlin
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Tag settings
tag_page_layout: tag_page
tag_page_dir: /tag

# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll/tagging
  
sass:
  sass_dir: assets/
  style: compressed
